#!/usr/bin/env bash
# https://www.lifewire.com/change-the-efi-boot-order-efibootmgr-4028027
REBOOT=false
SHUTDOWN=false

while test $# -gt 0
do
        case "$1" in
                --reboot) REBOOT=true
                ;;
                --restart) REBOOT=true
                ;;
                --shutdown) SHUTDOWN=true
                ;;
        *) echo "Invalid argument"
                exit
                ;;
        esac
        shift
done

sudo efibootmgr -o 0,1

if [[ "${REBOOT}" == "true" ]]; then
    sudo shutdown -r now
fi
if [[ "${SHUTDOWN}" == "true" ]]; then
    sudo shutdown -h now
fi

